"""Newsletter builder - assembles news into concise HTML email."""
import logging
from datetime import datetime, timezone, timedelta
from .news_collector import Article
logger = logging.getLogger(__name__)

def _now():
    return datetime.now(timezone(timedelta(hours=8))).strftime("%Y-%m-%d %A")

def build_list(items, label):
    if not items:
        return f'<p style="color:#999;font-style:italic;">No {label} today.</p>'
    rows = []
    for i, a in enumerate(items, 1):
        s = a.summary or "Click title to read full article"
        rows.append(
            f'<tr><td style="padding:10px 0;border-bottom:1px solid #eee;">'
            f'<span style="color:#999;font-size:12px;">{i:02d}.</span> '
            f'<a href="{a.url}" style="color:#333;text-decoration:none;font-weight:bold;font-size:14px;">{a.title}</a>'
            f'<div style="color:#666;font-size:13px;margin:3px 0;">{s}</div>'
            f'<div style="color:#aaa;font-size:11px;">{a.source}</div></td></tr>'
        )
    return "<table>" + "".join(rows) + "</table>"

def build_newsletter_html(en, zh):
    d = _now()
    en_html = build_list(en, "EN")
    zh_html = build_list(zh, "ZH")
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,'PingFang SC','Microsoft YaHei',sans-serif;">
<table width="100%"><tr><td align="center" style="padding:20px 10px;">
<table width="600" style="max-width:600px;width:100%;background:#fff;border-radius:8px;">
<tr><td style="background:linear-gradient(135deg,#1a365d,#2d6da8);padding:28px 30px;">
<div style="color:#fff;font-size:22px;font-weight:bold;">Elevator Daily News</div>
<div style="color:rgba(255,255,255,0.75);font-size:13px;margin-top:6px;">{d} | {len(en)+len(zh)} articles</div>
</td></tr>
<tr><td style="padding:24px 30px;">
<div style="font-size:15px;font-weight:bold;color:#1a365d;border-bottom:2px solid #1a365d;padding-bottom:8px;margin-bottom:8px;">English News</div>
{en_html}
<div style="height:1px;background:#e0e0e0;margin:16px 0;"></div>
<div style="font-size:15px;font-weight:bold;color:#c0392b;border-bottom:2px solid #c0392b;padding-bottom:8px;margin-bottom:8px;">Chinese News</div>
{zh_html}
</td></tr>
<tr><td style="background:#fafafa;padding:20px 30px;font-size:12px;color:#999;">
Generated by Elevator Daily News | Sources: elevatorworld.com / Baidu News / 36kr | Contact: noah30@qq.com
</td></tr>
</table></td></tr></table></body></html>"""

def build_plain_text(en, zh):
    lines = ["="*50, f"  Elevator Daily News - {_now()}", "="*50, ""]
    lines.append("--- English News ---")
    for a in en:
        lines += [f"{a.title}", f"  {a.summary}", f"  {a.url}", ""]
    lines.append("--- Chinese News ---")
    for a in zh:
        lines += [f"{a.title}", f"  {a.summary}", f"  {a.url}", ""]
    return "\n".join(lines)
